name: Gemini Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai requests

      - name: Run Gemini Code Review
        id: gemini-review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python gemini_review.py
          review_text=$(cat review_output.txt || echo "")
          echo "review_text<<EOF" >> $GITHUB_OUTPUT
          echo "$review_text" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Gemini Review as Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🤖 Gemini Code Review
            ${{ steps.gemini-review.outputs.review_text }}
